version: "3.2"
services:
  web:
    image: kun391/nino:1.0
    ports:
      - 8000:80
    container_name: "web"
    working_dir: /usr/var/app
    volumes:
      - .:/usr/var/app
      - ./build:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    command:
    - /bin/bash
    - -c
    - |
      service nginx restart
      tail -f /dev/null 2>&1
    restart: on-failure